### ISSUE TITLE
Shouldn't use transform here!

### ISSUE THREAD

**Issue by iqxtreme** [needle-mirror/com.unity.xr.interaction.toolkit#1]
https://github.com/needle-mirror/com.unity.xr.interaction.toolkit/blob/290bb69654476cd74de27b228f93fe2382fe2f72/Runtime/Interaction/Interactables/XRGrabInteractable.cs#L535

Shouldn't use ```transform.TransformDirection(m_InteractorLocalPosition)``` here because ```m_InteractorLocalPosition``` is not related to ```transform```, using ```transform``` here is meaningless.

The correction is to replace ```transform.TransformDirection(m_InteractorLocalPosition)``` with ```GetAttatchTransform(interactor).TransformDirection(m_InteractorLocalPosition)```.

The whole method should be corrected like below:
```
Vector3 GetWorldAttachPosition(IXRInteractor interactor)
{
            var interactorAttachTransform = interactor.GetAttachTransform(this);

            if (!m_TrackRotation)
                return interactorAttachTransform.position + 
GetAttatchTransform(interactor).TransformDirection(m_InteractorLocalPosition); 
// the following is replaced: transform.TransformDirection(m_InteractorLocalPosition);

            return interactorAttachTransform.position + interactorAttachTransform.rotation * m_InteractorLocalPosition;
}
```

**Comment by marwie** [comment]
Hello please [report this bug to Unity](https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-) - otherwise  it won't reach the devs here (needle-mirror is not affiliated with Unity).

In the meantime you can fork the repo and fix it there (if you haven't already)
